In [1]:
from keras.layers import Lambda, Input
from keras.models import Model

Using TensorFlow backend.


In [12]:
x = Input((1,))
y = Lambda(lambda x: x + 21)(x)
m = Model(x, y)

In [13]:
yp = m.predict_on_batch([1, 2, 3])
print('np.array([1,2,3]) + 1:')
print(yp)

np.array([1,2,3]) + 1:
[[22.]
 [23.]
 [24.]]


In [14]:
def kproc(x):
    return x ** 2 + 2 * x +1

In [15]:
def kshape(input_shape):
    return input_shape

In [16]:
x = Input((1,))
y = Lambda(kproc, kshape)(x)
m = Model(x, y)

In [17]:
print(x)

Tensor("input_4:0", shape=(None, 1), dtype=float32)


In [18]:
print(y)

Tensor("lambda_4/add_1:0", shape=(None, 1), dtype=float32)


In [19]:
print(m)

In [20]:
yp = m.predict_on_batch([1,2,3])

In [21]:
print(yp)

[[ 4.]
 [ 9.]
 [16.]]


In [10]:
from keras import backend as K
import numpy as np

In [3]:
def kproc_concat(x):
    m = K.mean(x, axis=1, keepdims=True)
    d1 = K.abs(x - m)
    d2 = K.square(x - m)
    print('x', x)
    print('m', m)
    print('d1', d1)
    print('d2', d2)
    print('K.concatenate([x, d1, d2], axis=1)', K.concatenate([x, d1, d2], axis=1))
    return K.concatenate([x, d1, d2], axis=1)

In [4]:
def kshape_concat(input_shape):
    output_shape = list(input_shape)
    output_shape[1] *= 3
    print(input_shape)
    print(output_shape)
    return tuple(output_shape)

In [24]:
x = Input((3,))
y = Lambda(kproc_concat, kshape_concat)(x)
m = Model(x, y)
print('... x', x)
print('... y', y)
print('... m', m)

x Tensor("input_5:0", shape=(None, 3), dtype=float32)
m Tensor("lambda_5/Mean:0", shape=(None, 1), dtype=float32)
d1 Tensor("lambda_5/Abs:0", shape=(None, 3), dtype=float32)
d2 Tensor("lambda_5/Square:0", shape=(None, 3), dtype=float32)
K.concatenate([x, d1, d2], axis=1) Tensor("lambda_5/concat:0", shape=(None, 9), dtype=float32)
(None, 3)
[None, 9]
... x Tensor("input_5:0", shape=(None, 3), dtype=float32)
... y Tensor("lambda_5/concat_1:0", shape=(None, 9), dtype=float32)
... m <keras.engine.training.Model object at 0x7fdf2b41c2d0>


In [26]:
print(m.summary())
xp = np.array([[1, 2, 3], [3, 4, 8], [3, 4, 8]])  # numpy로 변환하지 않으면 오류 발생
print('shape(xp)', xp.shape )
print('xp', xp)
yp = m.predict_on_batch(xp)

print(yp)

Model: "model_5"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_5 (InputLayer)         (None, 3)                 0         
_________________________________________________________________
lambda_5 (Lambda)            (None, 9)                 0         
Total params: 0
Trainable params: 0
Non-trainable params: 0
_________________________________________________________________
None
shape(xp) (3, 3)
xp [[1 2 3]
 [3 4 8]
 [3 4 8]]
[[1. 2. 3. 1. 0. 1. 1. 0. 1.]
 [3. 4. 8. 2. 1. 3. 4. 1. 9.]
 [3. 4. 8. 2. 1. 3. 4. 1. 9.]]
